### PR TITLE
#85 fixed

### PR DESCRIPTION
**Pull request by Duboviy91**
Now have a chance to get metanorma and metanorma-cli versions

### CODE REVIEW

**Comment by CAMOBAP795** [comment]
@Duboviy91 thanks for PR, may I quickly ask you to check why tests failed, looks like this happens after https://github.com/metanorma/metanorma-cli/commit/20ecb413ac5045e5182db66ea18ad2ad3957f085

**Comment by abunashir** [comment]
@CAMOBAP795: The test failures might be related to this one #109

**Comment by CAMOBAP795** [comment]
- blocked by https://github.com/metanorma/metanorma-standoc/pull/102

**Comment by ronaldtse** [comment]
@CAMOBAP795 can we merge this?

**Comment by CAMOBAP795** [comment]
@ronaldtse I think so

**Pull request merged**
