### PR TITLE
Fix base asset path related issue

### PR DESCRIPTION
**Pull request by abunashir**
### Work In Progress!

Debug helper:

```
docxml.to_s.lines.select { |line| !line.scan(/image-01.png/).empty? }
```
Related #242

### CODE REVIEW

**Comment by opoudjis** [comment]
word issue and pdf issue resolved.

**Comment by abunashir** [comment]
Update: Looks like it's working fine without the base path now and my apologies for the earlier comment, I might have some outdated gems or something.

@ronaldtse, @opoudjis: Since, this a default value and we don't necessarily need this, so I assume we can close this pull request?

**Comment by opoudjis** [comment]
Yes, and happy to merge it; I'm releasing from Draft. There is an issue in GHA with URI gem, but I've removed that dependency in metanorma-ietf, so it will go away.

**Comment by ronaldtse** [comment]
@opoudjis are you saying that the PR now works?

Question: why is `baseassetpath` not using the snake case convention? i.e. `base_asset_path`?

**Comment by opoudjis** [comment]
> @opoudjis are you saying that the PR now works?

Yes.

> Question: why is `baseassetpath` not using the snake case convention? i.e. `base_asset_path`?

Shrug. Most of them are not...

**Comment by ronaldtse** [comment]
> Question: why is baseassetpath not using the snake case convention? i.e. base_asset_path?

Let's all follow the Ruby convention... please...

**Pull request merged**
