### PR TITLE
#301 return non-zero exit code on fatal errors

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #301

### CODE REVIEW

**Comment by CAMOBAP** [comment]
Locally I have strange crash, but there is no it on CI

```
     NoMethodError:
       undefined method `svgmap_rewrite' for Metanorma::Utils:Module
     # ./lib/metanorma/cli/collection.rb:19:in `render'
     # ./lib/metanorma/cli/collection.rb:14:in `render'
     # ./lib/metanorma/cli/command.rb:76:in `collection'
     # ./lib/metanorma/cli.rb:34:in `start'
     # ./spec/acceptance/collection_spec.rb:32:in `block in run_metanorma_collection'
     # ./spec/support/console_helper.rb:8:in `capture_stdout'
     # ./spec/acceptance/collection_spec.rb:32:in `run_metanorma_collection'
     # ./spec/acceptance/collection_spec.rb:6:in `block (3 levels) in <top (required)>'
     # ./spec/acceptance/collection_spec.rb:19:in `block (4 levels) in <top (required)>'
     # ./spec/acceptance/collection_spec.rb:19:in `chdir'
     # ./spec/acceptance/collection_spec.rb:19:in `block (3 levels) in <top (required)>'
     # ./spec/acceptance/collection_spec.rb:17:in `block (2 levels) in <top (required)>'
```

**Comment by ronaldtse** [comment]
Maybe this has to do with the recent refactor for the new Vectory gem. Ping @alexeymorozov.

**Comment by alexeymorozov** [comment]
> svgmap_rewrite

Yes, high chance it is connected. Vectory is used now in code and a gemspec. One or all of the following gems need to be updated locally:

- https://github.com/metanorma/metanorma/blob/main/metanorma.gemspec
- https://github.com/metanorma/isodoc/blob/main/isodoc.gemspec
- https://github.com/metanorma/metanorma-standoc/blob/main/metanorma-standoc.gemspec
- https://github.com/metanorma/metanorma-ietf/blob/main/metanorma-ietf.gemspec

**Comment by opoudjis** [comment]
There shall be a single point of dependency to vectory, html2doc.

**Pull request merged**
