### PR TITLE
#177 don't use 'git ls-file' for spec.files as bad practice

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #177

### CODE REVIEW

**Comment by CAMOBAP** [comment]
I tried to find some general solution like `git ls-files -z` but unfortunately didn't find it. what I have tried:
 - https://stackoverflow.com/questions/11873294/determining-the-gems-list-of-files-for-the-specification

But the best one is just listed files to include in gem

**Review by opoudjis — APPROVED** [review]
I'm  not ecstatic about this, because during debugging I may leave other files lying around, but I don't have a better suggestion...

**Comment by CAMOBAP** [comment]
@opoudjis @ronaldtse @andrew2net maybe we should keep `git ls-files -z` as the primary way to get gem files but also use this solution as 'fallback' (in case if source have no git installed or have no .git directory)

How do you think?

**Comment by andrew2net** [comment]
@CAMOBAP I think we should keep `git ls-files -z` unless it causes an issue.

**Comment by CAMOBAP** [comment]
@andrew2net it cause the issue when we build a gem from zip archive which downloaded from GH

**Pull request merged**
