### PR TITLE
Travis add OSX to test

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- https://github.com/metanorma/metanorma/issues/41#issuecomment-475667097

### CODE REVIEW

**Comment by CAMOBAP795** [comment]
Run time increased to 35m

**Comment by CAMOBAP795** [comment]
@ronaldtse @opoudjis how do you think is it make sense to proceed with OSX for another repos?

**Comment by ronaldtse** [comment]
@camobap795 please help apply this change to the other repos too. Thanks!

**Comment by CAMOBAP795** [comment]
@ronaldtse sure, https://github.com/metanorma/metanorma/issues/46 - reported to track progress

**Pull request merged**
