### PR TITLE
#122 remove duplicates from version commands

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- #122

### CODE REVIEW

**Comment by CAMOBAP795** [comment]
> We should fix the problem where processors should not be registered more than once. The current change does not fix the real problem.

I think it will fix the problem because we use the same processor for two types of docs

csand => {Metanorma::Csand::Processor} #<Metanorma::Csand::Processor:0x00007fe4c204bc68>
csa => {Metanorma::Csand::Processor} #<Metanorma::Csand::Processor:0x00007fe4c204bc68>

**Comment by ronaldtse** [comment]
@CAMOBAP795 I see! In this case, the better fix would be to remove the "csand" abbreviation and completely change to "csa"...

**Comment by CAMOBAP795** [comment]
@ronaldtse to be on the same page you propose to replace this array https://github.com/metanorma/metanorma-csand/blob/master/lib/metanorma/csand/processor.rb#L8 with a single value `:csa`, right?

**Comment by CAMOBAP795** [comment]
@ronaldtse @andrew2net how do you feel about the comment above?

**Comment by ronaldtse** [comment]
> @ronaldtse to be on the same page you propose to replace this array https://github.com/metanorma/metanorma-csand/blob/master/lib/metanorma/csand/processor.rb#L8 with a single value `:csa`, right?

Yes, let's do that. We should also change all the instances of `csand` within `metanorma-csa` gem.

**Comment by CAMOBAP795** [comment]
@ronaldtse got you, in this case, I'm closing this PR

**Pull request closed without merging**
