### PR TITLE
metanorma/metanorma-build-scripts#18 add ruby 2.6 to CI matrix

### PR DESCRIPTION
**Pull request by CAMOBAP795**

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP795 AppVeyor build is failing. What kind of fix is needed?

**Comment by CAMOBAP795** [comment]
@ronaldtse 3 gems need to be released 

 - https://github.com/metanorma/relaton-bib/
 - https://github.com/metanorma/relaton-iso-bib/
 - https://github.com/metanorma/iso-bib-item/

[more details](https://github.com/metanorma/metanorma-build-scripts/issues/18#issuecomment-513226142)

**Comment by CAMOBAP795** [comment]
@ronaldtse 
 - release a new version of `relaton-bib`
 - merge https://github.com/metanorma/relaton-iso-bib/pull/4
 - merge https://github.com/metanorma/iso-bib-item/pull/11
 - release a new version of `relaton-iso-bib`
 - release a new version of `iso-bib-item`

**Comment by ronaldtse** [comment]
@CAMOBAP795 thanks for the steps:

Adding responsibilities:
 - (@andrew2net) release a new version of `relaton-bib`
 - (@andrew2net) merge https://github.com/metanorma/relaton-iso-bib/pull/4
 - (@andrew2net) merge https://github.com/metanorma/iso-bib-item/pull/11
 - (@andrew2net) release a new version of `relaton-iso-bib`
 - (@andrew2net) release a new version of `iso-bib-item` -- But this gem is already deprecated. Where are we using it? We should remove the dependency.

**Comment by ronaldtse** [comment]
@CAMOBAP795 can you also help merge the rest of the issues about 2.6 if they are all passing? Thanks.

**Comment by CAMOBAP795** [comment]
@ronaldtse sure

**Pull request merged**
