### PR TITLE
Feature/socks proxy support

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #202
 - #248

Related PR https://github.com/metanorma/metanorma.org/pull/455

### CODE REVIEW

**Comment by CAMOBAP** [comment]
I still need to test it on some local SOCKS5 proxy

**Comment by CAMOBAP** [comment]
Tested with https://github.com/rofl0r/microsocks and `Sockify::debug = true` to check that traffic comes through proxy

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP !

**Comment by ronaldtse** [comment]
We just need a GHA to ensure this continues to work.

**Pull request merged**
