### PR TITLE
metanorma/metanorma-docker#87 trigger specific docker image

### PR DESCRIPTION
**Pull request by CAMOBAP**
- metanorma/metanorma-docker#87
 - related branch on metanorma-docker https://github.com/metanorma/metanorma-docker/tree/feature/pres_xml

### CODE REVIEW

**Comment by opoudjis** [comment]
@CAMOBAP This is failing GitHub Actions; the errors seem to be:

lib/metanorma/cli/setup.rb:62: `if response.downcase === "yes"` failing with response being nil, should this be `response&.downcase`?

spec/acceptance/version_spec.rb:22: `expect(output).to include("Metanorma::Csd #{Metanorma::Csd::VERSION}")` becomes `expect(output).to include("Metanorma::CC #{Metanorma::CC::VERSION}")`

lib/metanorma/cli/setup.rb:63: generating an HTTP 404 error

spec/acceptance/list_extensions_spec.rb, spec/acceptance/list_extensions_spec.rb:16: needs to be updated to include the new "presentation" output format

Could you please review these, particularly the HTTP 404?

**Comment by CAMOBAP** [comment]
@opoudjis @Intelligent2013 it fails because of 

```
Traceback (most recent call last):
	32: from /Users/camobap/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bin/metanorma:23:in `<main>'
	31: from /Users/camobap/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bin/metanorma:23:in `load'
	30: from /Users/camobap/Developers/Projects/riboseinc/cimas-root/metanorma-cli/exe/metanorma:20:in `<top (required)>'
	29: from /Users/camobap/Developers/Projects/riboseinc/cimas-root/metanorma-cli/lib/metanorma/cli.rb:74:in `start'
	28: from /Users/camobap/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	27: from /Users/camobap/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	26: from /Users/camobap/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	25: from /Users/camobap/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	24: from /Users/camobap/Developers/Projects/riboseinc/cimas-root/metanorma-cli/lib/metanorma/cli/command.rb:36:in `compile'
	23: from /Users/camobap/Developers/Projects/riboseinc/cimas-root/metanorma-cli/lib/metanorma/cli/compiler.rb:33:in `compile'
	22: from /Users/camobap/Developers/Projects/riboseinc/cimas-root/metanorma-cli/lib/metanorma/cli/compiler.rb:29:in `compile'
	21: from /Users/camobap/Developers/Projects/riboseinc/cimas-root/metanorma-cli/lib/metanorma/cli/compiler.rb:41:in `compile_file'
	20: from /Users/camobap/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-1.1.2/lib/metanorma/compile.rb:24:in `compile'
	19: from /Users/camobap/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-1.1.2/lib/metanorma/compile.rb:234:in `process_extensions'
	18: from /Users/camobap/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-1.1.2/lib/metanorma/compile.rb:234:in `each'
	17: from /Users/camobap/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-1.1.2/lib/metanorma/compile.rb:245:in `block in process_extensions'
	16: from /Users/camobap/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-iso-1.4.2/lib/metanorma/iso/processor.rb:44:in `output'
	15: from /Users/camobap/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/isodoc-1.1.2/lib/isodoc/html_convert.rb:24:in `convert'
	14: from /Users/camobap/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/isodoc-1.1.2/lib/isodoc/convert.rb:233:in `convert'
	13: from /Users/camobap/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/metanorma-iso-1.4.2/lib/isodoc/iso/base_convert.rb:28:in `convert1'
	12: from /Users/camobap/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/isodoc-1.1.2/lib/isodoc/html_function/html.rb:8:in `convert1'
	11: from /Users/camobap/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/isodoc-1.1.2/lib/isodoc/function/utils.rb:31:in `noko'
	10: from /Users/camobap/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:254:in `with'
	 9: from /Users/camobap/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:254:in `new'
	 8: from /Users/camobap/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:295:in `initialize'
	 7: from /Users/camobap/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/isodoc-1.1.2/lib/isodoc/html_function/html.rb:9:in `block in convert1'
	 6: from /Users/camobap/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:377:in `method_missing'
	 5: from /Users/camobap/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:394:in `insert'
	 4: from /Users/camobap/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/isodoc-1.1.2/lib/isodoc/html_function/html.rb:11:in `block (2 levels) in convert1'
	 3: from /Users/camobap/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/isodoc-1.1.2/lib/isodoc/convert.rb:107:in `populate_css'
	 2: from /Users/camobap/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/isodoc-1.1.2/lib/isodoc/convert.rb:183:in `generate_css'
	 1: from /Users/camobap/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/isodoc-1.1.2/lib/isodoc/convert.rb:163:in `convert_scss'
/Users/camobap/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/isodoc-1.1.2/lib/isodoc/convert.rb:163:in `require': cannot load such file -- sassc (LoadError)
```

If I will return `spec.add_development_dependency "sassc", "2.4.0"` back to gemspec it will works, but I'm not sure that it's a right fix

**Comment by opoudjis** [comment]
@CAMOBAP doing the hotfix now, try it out again in a couple of hours

**Comment by opoudjis** [comment]
metanorma-cli just released, with the stack hotfixed to use css instead of scss, so sassc dependency *should* no longer be an issue.

**Comment by opoudjis** [comment]
@CAMOBAP @abunashir retested with fixed stack, still failing, but now failing in Ubuntu on fontist:

https://github.com/metanorma/metanorma-cli/pull/160/checks?check_run_id=923737308

**Comment by abunashir** [comment]
Yap, I think it's using an outdated master that is still using [`fontist 0.2`](https://github.com/metanorma/metanorma-cli/pull/160/checks?check_run_id=923737308#step:4:149), the current master should fix this issue, please let me know if there is still some issue after rebasing it with the master.

**Comment by ronaldtse** [comment]
Branch pres_xml has been merged to master. Thanks @CAMOBAP for this PR which helped @opoudjis with the testing! Closing this now.

**Pull request closed without merging**
