### PR TITLE
Update base template for new document

### LINKED ISSUE #60: Update base templates (current Travis one not working)
Use this travis config:
* https://github.com/metanorma/csa-caiq/blob/master/.travis.yml

Use this Makefile:
* https://github.com/metanorma/csa-caiq/blob/master/Makefile

Use this gitignore:
* https://github.com/metanorma/csa-caiq/blob/master/.gitignore

Remove `deploy.sh` (the Travis script uses https://github.com/metanorma/metanorma-build-scripts/blob/master/deploy-to-gh-pages.sh)

### PR DESCRIPTION
**Pull request by abunashir**
This commit updates the base templates as described in issue #60

Closes #60

### CODE REVIEW

**Comment by ronaldtse** [comment]
@abunashir thanks! 

1. The specs are failing
2. For the Makefile, we need to make sure all “targets” (the code under every “foobar:”) starts with a tab; it looks like the white spaces have been changed. Of the tabs are replaced with spaces the command will fail. Could you help check?

**Comment by ronaldtse** [comment]
We also want to test that these files actually work, let’s do that in a new PR. 

Ie. “make” command to test Makefile. “make” on Windows (AppVeyor) to test Makefile.win.

**Comment by abunashir** [comment]
My bad, I was copying without paste mode on, but now it should be fixed, and also the specs. thanks @ronaldtse!

> @abunashir thanks!
> 
> 1. The specs are failing
> 2. For the Makefile, we need to make sure all “targets” (the code under every “foobar:”) starts with a tab; it looks like the white spaces have been changed. Of the tabs are replaced with spaces the command will fail. Could you help check?

**Comment by ronaldtse** [comment]
Thanks @abunashir !

**Pull request merged**
