### PR TITLE
Simplify appveyor script

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- https://github.com/metanorma/metanorma/issues/41

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP795 All builds are failing. Can you take a look? Or is this for @opoudjis ?

**Comment by CAMOBAP795** [comment]
@ronaldtse @opoudjis according to history tests was broken in https://github.com/metanorma/metanorma-cli/commit/9dc2cc2d83b8203277a521d413fab956c2a30739 commit

**Comment by opoudjis** [comment]
Bear in mind you did this while I was making breaking changes to gems. If travis breaks, you're off the hook.

**Comment by CAMOBAP795** [comment]
@opoudjis ok)

**Pull request merged**
